language: node_js
node_js:
    - 'node'

addons:
  ssh_known_hosts:
    - ec2-3-138-105-146.us-east-2.compute.amazonaws.com
  sonarcloud:
    organization: "fga-eps-mds-1"
    token: ${SONAR_TOKEN} 

services:
- docker

notifications:
    email: false

branches:
only:
    - master
    - development    

before_script:
    - npm install
    - sonar-scanner -Dsonar.projectKey=fga-eps-mds_2020.1-VC_Gestor-FrontEnd

script:
  - npm run test && chmod 400 deploy_rsa;

deploy:
  provider: script
  script: 
    - bash deploy.sh ${TRAVIS_BRANCH}
  on:
    branch: master 
