language: node_js
node_js:
    - 'node'

addons:
  ssh_known_hosts:
    - ec2-3-138-105-146.us-east-2.compute.amazonaws.com

services:
- docker

notifications:
    email: false

branches:
only:
    - master
    - development

before_script:
    - npm install

script:
  - npm run test && chmod 400 deploy_rsa;

deploy:
  provider: script
  script: 
    - bash deploy.sh
  on:
    branch: master 
