language: node_js
node_js:
    - 'node'

notifications:
    email: false
    
cache:
  directories:
  - node_modules

branches:
only:
    - master
    - development
    - Issue_145-NewsTest
    - Issue_152-BenefitsTest

before_script:
    - npm install

script:
  - npm run test
