version: '3.7'

services:

  vamos-cuidar-gestor:
    container_name: vamos-cuidar-gestor
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks: 
      20201-vc_gestor-backend_backend:
        ipv4_address: 172.25.0.5 
networks:
  20201-vc_gestor-backend_backend:
      external: True